#+TITLE: The Gesture Path
* Overview
This document implements a Lua interface for create Gesture
Paths for Gesture VM. Paths constructed in Lua eventually
get generated into @!(ref "tal")!@ code.
* What's a "Path"?
A *path* is a construct used to describe Gestures. This
is a term borrowed from computer science and graph
theory. A path
can be described as a sequential set of vertices,
connected together by edges. In this context,
a vertice can be thought of as a set of state parameters
for the Gesture Signal Generator: value, behavior, and
rate multiplier. Alternatively, one could also imagine
edges as being weighted by the rate multiplier, but at
the time of writing there hasn't been any usecase for
doing it this way.

A path is said to be *linear* if the vertices flow in
one single direction. A path becomes *non-linear* when this
flow is interrupted somehow, such as with branching.
* Tangled Code
#+NAME: path.lua
#+BEGIN_SRC lua :tangle path/path.lua
local Path = {}

function Path.path(tal, words, path)
    for _, v in pairs(path)
    do
        if v.val ~= nil then
            tal.val(words, v.val)
        end

        if v.dur ~= nil then
            tal.dur(words, v.dur[1], v.dur[2])
        end

        if v.bhvr ~= nil then
            tal.behavior(words, v.bhvr)
        end
    end
end

function Path.vertex(v)
    x = {}

    x.val = v[1]
    x.dur = v[2]
    x.bhvr = v[3]

    return x
end

return Path
#+END_SRC
