#+TITLE: Runes
* Overview
Runes are the name given to the main glyph in
a @!(ref "sigils" "gesture sigil")!@. They are represented
as 7x7 1-bit tiles, and typically conform to the aesthetic
rules of Square Kufic calligraphy which impose a balance
of black and white tiles.

When rendering a Gesture Sigil, the Rune gets doubled in
size to take up a 14x14 pixel space inside of a 16x16
pixel area. The remaining pixels serve as padding.
* Tangled Files
Runes are stored in a text file format readable by
the @!(ref "loadtiles")!@ function.

#+NAME: runes.txt
#+BEGIN_SRC txt :tangle runes/runes.txt
<<runes>>
#+END_SRC

A corresponding janet file called "runes.janet" will
be used to help look up runes in a tile map (8x8 tilemap,
or 64 runes max).

#+NAME: runes.janet
#+BEGIN_SRC janet :tangle runes/runes.janet
(def runes @{
<<entries>>
})
(do
  (def loadtiles-file (dofile "loadtiles/loadtiles.janet"))
  (def gen-tilemap ((loadtiles-file 'gen-tilemap) :value))
  (def tmap
    (gen-tilemap "runes/runes.txt" 7 7 8 8))

  (def canvas @[0 0 (* 48 8) (* 48 8)])
  (def bp (btprnt/new (canvas 2) (canvas 3)))

  (def zoom 2)

  (def geneva9 (btprnt/macfont-load "fonts/geneva_9"))


  (each k (keys runes)
    (def glyph (runes k))
    (def grid (btprnt/grid
                bp canvas 8 8 (glyph 0) (glyph 1)))
    (def text (string k))

    (btprnt/macfont-textbox
      bp geneva9 
      grid
      (math/floor
        (- (/ (grid 2) 2)
           (/ (btprnt/macfont-linewidth geneva9 text) 2)))
      (- (grid 3) 13) text 1)

    (def center (btprnt/centerbox 
                  bp
                  grid
                  (+ (* 7 zoom) 2)
                  (+ (* 7 zoom) 2)))

    (btprnt/outline bp center 1)
    (btprnt/tile
      bp tmap
      center
      1 1
      (glyph 0) (glyph 1)
      7 7
      zoom 1)
    )


  (btprnt/write-pbm bp "runes.pbm")
  (btprnt/del bp)
  (btprnt/del tmap)
  )
#+END_SRC
* Empty Space
#+NAME: runes
#+BEGIN_SRC txt
-------
-------
-------
-------
-------
-------
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:empty @[0 0]
#+END_SRC
* Chinese Number Inspired Runes
These are runes based on the chinese numbers 1-8.
** One ("yi1")
#+NAME: runes
#+BEGIN_SRC txt
-------
#######
#-----#
#-###-#
#-----#
#######
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:yi @[1 0]
#+END_SRC
** Two ("er4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-----#
#-###-#
-------
-#####-
-------
###-###
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:er @[2 0]
#+END_SRC
** Three ("san1")
#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
-------
#-###-#
-------
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:san @[3 0]
#+END_SRC
** Four ("si4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-#-#-#
###-###
#-----#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:si @[4 0]
#+END_SRC
** Five ("wu3")
Five was a difficult one to port over, so I
didn't bother.

#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
---#---
##-#-##
---#---
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:wu @[5 0]
#+END_SRC
** Six ("liu4")
The character is in here if you look hard enough.

#+NAME: runes
#+BEGIN_SRC txt
-#-#-#-
##-#-##
-------
-#####-
-------
-#-#-#-
---#---
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:liu @[6 0]
#+END_SRC
** Seven ("qi1")
#+NAME: runes
#+BEGIN_SRC txt
-#####-
-#---#-
---#---
#-###-#
#--#--#
##-##-#
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:qi @[7 0]
#+END_SRC
** Eight ("ba1")
#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-#-#-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ba @[0 1]
#+END_SRC
* Some Early Prototypes
These are some early sigils I worked out.
** Diamond
My first instinct was to draw a diamond. I always
like starting at the center, and then going out.
This also reminds me of one of those oriental rug patterns.

#+NAME: runes
#+BEGIN_SRC txt
##---##
#--#--#
--###--
-##-##-
--###--
#--#--#
##---##
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:diamond @[1 1]
#+END_SRC
** Asymmetrical
I tried going against my instinct of starting in the center,
and instead tried to do something that was lopsided and
asymetrical. Kufic rules enforce a certain kind of balance
and order.

#+NAME: runes
#+BEGIN_SRC txt
##-####
#-----#
#-#-#--
--#-#-#
#---#--
#-####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:asym @[2 1]
#+END_SRC
** T Tile
Playing with asymmetry more, I wanted to explore using
tesselations and motifs within the limited space.

This was built up using a "T" radical.

These kinds of runes to me are less rune, more texture.

#+NAME: runes
#+BEGIN_SRC txt
###---#
-#--#-#
---##--
-#--#-#
###---#
----#--
-#-###-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ttile @[3 1]
#+END_SRC
** Box in a Box
The Box. Inside a Box. Runes like these are always the
clearest.

#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:boxinbox @[4 1]
#+END_SRC
* Sanskrit Inspired
These are sets adapted from the Candy Crystal Codex, which
were loosely inspired by Sanskrit symbols.

The Codex symbols are 8x8. They will need to scrunch into
7x7.

These may adhere to Kufic rules, but maybe not.

The Codex was originally going to
be written in generative Kufic, but I didn't have the
code ready for that. The Sanskrit glyphs were a backup.
Funnily enough, these Sanskrit symbols I made are perhaps
more apt for this system than some of the initial
Kufic symbols I wrote.

#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
-#--#--
-#--#--
-#--#--
-#--#--
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit1 @[5 1]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-#####-
---#-#-
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit2 @[6 1]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#---#-
-#--##-
-#---#-
-##-##-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit3 @[7 1]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
---###-
-#-#-#-
-###-#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit4 @[0 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-#####-
-#---#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit5 @[1 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
----#--
-#-###-
-###-#-
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit6 @[2 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
-###-##
-#-#-#-
-###-#-
--#--#-
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit7 @[3 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
----#--
-####--
-#--#--
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit8 @[4 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
##-####
-#---#-
-----#-
-#-###-
####---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit9 @[5 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
--#--#-
-##--#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit10 @[6 2]
#+END_SRC


#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
--####-
-----#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit11 @[7 2]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
--####-
--#--#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit12 @[0 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-###-#-
-----#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit13 @[1 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
###-###
-#---#-
-#####-
-#-#-#-
-#-###-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit14 @[2 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-#-#-
-#---#-
-##----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit15 @[3 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
-#####-
---#-#-
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit16 @[4 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-###-
-#---#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit17 @[5 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-###---
-#-###-
-###---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit18 @[6 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
--------
#######
---#---
---###-
---#---
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit19 @[7 3]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
-#####-
-#-----
-#####-
---#-#-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit20 @[0 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
-#####-
-----#-
-#####-
-----#-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit21 @[1 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#-#-###
--#--#-
--##-#-
-----#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit22 @[2 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
##-#-##
---#-#-
-###-#-
-#-###-
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit23 @[3 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
-##-###
-##-#--
----#--
-#####-
-#---#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit24 @[4 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#---#-
-#####-
---#---
--##---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit25 @[5 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-#-#-
---#-##
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit26 @[6 4]
#+END_SRC

#+NAME: runes
#+BEGIN_SRC txt
-------
###-###
-#---#-
-#####-
---#---
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:sanskrit27 @[7 4]
#+END_SRC
