#+TITLE: Runes
* Overview
Runes are the name given to the main glyph in
a @!(ref "sigils" "gesture sigil")!@. They are represented
as 7x7 1-bit tiles, and typically conform to the aesthetic
rules of Square Kufic calligraphy which impose a balance
of black and white tiles.

When rendering a Gesture Sigil, the Rune gets doubled in
size to take up a 14x14 pixel space inside of a 16x16
pixel area. The remaining pixels serve as padding.
* Tangled Files
Runes are stored in a text file format readable by
the @!(ref "loadtiles")!@ function.

#+NAME: runes.txt
#+BEGIN_SRC txt :tangle runes/runes.txt
<<runes>>
#+END_SRC

A corresponding janet file called "runes.janet" will
be used to help look up runes in a tile map (8x8 tilemap,
or 64 runes max).

#+NAME: runes.janet
#+BEGIN_SRC janet :tangle runes/runes.janet
<<entries>>
#+END_SRC
* Empty Space
#+NAME: runes
#+BEGIN_SRC txt
-------
-------
-------
-------
-------
-------
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define yi @[0 0])
#+END_SRC
* Chinese Number Inspired Runes
These are runes based on the chinese numbers 1-8.
** One ("yi1")
#+NAME: runes
#+BEGIN_SRC txt
-------
#######
#-----#
#-###-#
#-----#
#######
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define yi @[1 0])
#+END_SRC
** Two ("er4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-----#
#-###-#
-------
-#####-
-------
###-###
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define er @[2 0])
#+END_SRC
** Three ("san1")
#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
-------
#-###-#
-------
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define san @[3 0])
#+END_SRC
** Four ("si4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-#-#-#
###-###
#-----#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define si @[4 0])
#+END_SRC
** Five ("wu3")
Five was a difficult one to port over, so I
didn't bother.

#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
---#---
##-#-##
---#---
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define wu @[5 0])
#+END_SRC
** Six ("liu4")
The character is in here if you look hard enough.

#+NAME: runes
#+BEGIN_SRC txt
-#-#-#-
##-#-##
-------
-#####-
-------
-#-#-#-
---#---
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define liu @[6 0])
#+END_SRC
** Seven ("qi1")
#+NAME: runes
#+BEGIN_SRC txt
-#####-
-#---#-
---#---
#-###-#
#--#--#
##-##-#
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define qi @[7 0])
#+END_SRC
** Eight ("ba1")
#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-#-#-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define ba @[0 1])
#+END_SRC
* Some Early Prototypes
These are some early sigils I worked out.
** Diamond
My first instinct was to draw a diamond. I always
like starting at the center, and then going out.
This also reminds me of one of those oriental rug patterns.

#+NAME: runes
#+BEGIN_SRC txt
##---##
#--#--#
--###--
-##-##-
--###--
#--#--#
##---##
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define diamond @[1 1])
#+END_SRC
** Asymmetrical
I tried going against my instinct of starting in the center,
and instead tried to do something that was lopsided and
asymetrical. Kufic rules enforce a certain kind of balance
and order.

#+NAME: runes
#+BEGIN_SRC txt
##-####
#-----#
#-#-#--
--#-#-#
#---#--
#-####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define asymm @[2 1])
#+END_SRC
** T Tile
Playing with asymmetry more, I wanted to explore using
tesselations and motifs within the limited space.

This was built up using a "T" radical.

These kinds of runes to me are less rune, more texture.

#+NAME: runes
#+BEGIN_SRC txt
###---#
-#--#-#
---##--
-#--#-#
###---#
----#--
-#-###-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define ttile @[3 1])
#+END_SRC
** Box in a Box
The Box. Inside a Box. Runes like these are always the
clearest.

#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
(define box-in-box @[4 1])
#+END_SRC
* Sanskit Inspired
These are sets adapted from the Candy Crystal Codex, which
were loosely inspired by Sanskrit symbols.

These may adhere to Kufic rules, but maybe not.
