#+TITLE: Runes
@!
(do
  (def runes (dofile "runes/runes.janet"))
  (def runes-png ((runes 'runes-png) :value))
  (def bp (runes-bp))
  (bpimg bp "runeset chart")
  (btprnt/del bp))
!@
* Overview
Runes are the name given to the main glyph in
a @!(ref "sigils" "gesture sigil")!@. They are represented
as 7x7 1-bit tiles, and typically conform to the aesthetic
rules of Square Kufic calligraphy which impose a balance
of black and white tiles.

When rendering a Gesture Sigil, the Rune gets doubled in
size to take up a 14x14 pixel space inside of a 16x16
pixel area. The remaining pixels serve as padding.
* Tangled Files
Runes are stored in a text file format readable by
the @!(ref "loadtiles")!@ function.

#+NAME: runes.txt
#+BEGIN_SRC txt :tangle runes/runes.txt
<<runes>>
#+END_SRC

A corresponding janet file called "runes.janet" will
be used to help look up runes in a tile map (8x8 tilemap,
or 64 runes max).

#+NAME: runes.janet
#+BEGIN_SRC janet :tangle runes/runes.janet
(def runes @{
<<entries>>
})

(defn runes-bp []
  (def loadtiles-file (dofile "loadtiles/loadtiles.janet"))
  (def gen-tilemap ((loadtiles-file 'gen-tilemap) :value))
  (def tmap
    (gen-tilemap "runes/runes.txt" 7 7 8 8))

  (def canvas @[0 0 (* 48 8) (* 48 8)])
  (def bp (btprnt/new (canvas 2) (canvas 3)))

  (def zoom 2)

  (def geneva9 (btprnt/macfont-load "fonts/geneva_9"))


  (each k (keys runes)
    (def glyph (runes k))
    (def grid (btprnt/grid
                bp canvas 8 8 (glyph 0) (glyph 1)))
    (def text (string k))

    (btprnt/macfont-textbox
      bp geneva9 
      grid
      (math/floor
        (- (/ (grid 2) 2)
           (/ (btprnt/macfont-linewidth geneva9 text) 2)))
      (- (grid 3) 13) text 1)

    (def center (btprnt/centerbox 
                  bp
                  grid
                  (+ (* 7 zoom) 2)
                  (+ (* 7 zoom) 2)))

    (btprnt/outline bp center 1)
    (btprnt/tile
      bp tmap
      center
      1 1
      (glyph 0) (glyph 1)
      7 7
      zoom 1)
    )


  (btprnt/del tmap)
  bp)
#+END_SRC
* Empty Space
empty space.

#+NAME: runes
#+BEGIN_SRC txt
-------
-------
-------
-------
-------
-------
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:empty @[0 0]
#+END_SRC
* Chinese Number Inspired Runes
These are runes based on the chinese numbers 1-8.
** One ("yi1")
#+NAME: runes
#+BEGIN_SRC txt
-------
#######
#-----#
#-###-#
#-----#
#######
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:yi @[1 0]
#+END_SRC
** Two ("er4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-----#
#-###-#
-------
-#####-
-------
###-###
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:er @[2 0]
#+END_SRC
** Three ("san1")
#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
-------
#-###-#
-------
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:san @[3 0]
#+END_SRC
** Four ("si4")
#+NAME: runes
#+BEGIN_SRC txt
###-###
#-#-#-#
###-###
#-----#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:si @[4 0]
#+END_SRC
** Five ("wu3")
Five was a difficult one to port over, so I
didn't bother.

#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
---#---
##-#-##
---#---
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:wu @[5 0]
#+END_SRC
** Six ("liu4")
The character is in here if you look hard enough.

#+NAME: runes
#+BEGIN_SRC txt
-#-#-#-
##-#-##
-------
-#####-
-------
-#-#-#-
---#---
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:liu @[6 0]
#+END_SRC
** Seven ("qi1")
#+NAME: runes
#+BEGIN_SRC txt
-#####-
-#---#-
---#---
#-###-#
#--#--#
##-##-#
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:qi @[7 0]
#+END_SRC
** Eight ("ba1")
#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-#-#-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ba @[0 1]
#+END_SRC
* Some Early Prototypes
These are some early sigils I worked out.
** Diamond
My first instinct was to draw a diamond. I always
like starting at the center, and then going out.
This also reminds me of one of those oriental rug patterns.

#+NAME: runes
#+BEGIN_SRC txt
##---##
#--#--#
--###--
-##-##-
--###--
#--#--#
##---##
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:diamond @[1 1]
#+END_SRC
** Asymmetrical
I tried going against my instinct of starting in the center,
and instead tried to do something that was lopsided and
asymetrical. Kufic rules enforce a certain kind of balance
and order.

#+NAME: runes
#+BEGIN_SRC txt
##-####
#-----#
#-#-#--
--#-#-#
#---#--
#-####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:asym @[2 1]
#+END_SRC
** T Tile
Playing with asymmetry more, I wanted to explore using
tesselations and motifs within the limited space.

This was built up using a "T" radical.

These kinds of runes to me are less rune, more texture.

#+NAME: runes
#+BEGIN_SRC txt
###---#
-#--#-#
---##--
-#--#-#
###---#
----#--
-#-###-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ttile @[3 1]
#+END_SRC
** Box in a Box
The Box. Inside a Box. Runes like these are always the
clearest.

#+NAME: runes
#+BEGIN_SRC txt
#######
#-----#
#-###-#
#-#-#-#
#-###-#
#-----#
#######
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:boxinbox @[4 1]
#+END_SRC
* Sanskrit Inspired
These are sets adapted from the Candy Crystal Codex, which
were loosely inspired by Sanskrit symbols.

The Codex symbols are 8x8. They will need to scrunch into
7x7.

These may adhere to Kufic rules, but maybe not.

The Codex was originally going to
be written in generative Kufic, but I didn't have the
code ready for that. The Sanskrit glyphs were a backup.
Funnily enough, these Sanskrit symbols I made are perhaps
more apt for this system than some of the initial
Kufic symbols I wrote.

These runes will be introduced the proper Candy Crystal
Codex way, using procedurally generated names and
descriptions.
** ryshar
kigoh zusod cimee.

#+NAME: runes
#+BEGIN_SRC txt
-------
-#####-
-#--#--
-#--#--
-#--#--
-#--#--
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ryshar @[5 1]
#+END_SRC
** haerabeek
shocasheh zhemaej chomuz.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-#####-
---#-#-
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:haerabeek @[6 1]
#+END_SRC
** che
beenodeet cham laim.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#---#-
-#--##-
-#---#-
-##-##-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:che @[7 1]
#+END_SRC
** kat
pamaim rasab baifaevai shaer kae sutygi.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
---###-
-#-#-#-
-###-#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:kat @[0 2]
#+END_SRC
** lubigis
chaezeepab sheenaic shebyfer tog ship.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-#####-
-#---#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:lubigis @[1 2]
#+END_SRC
** kyvi
kohyjyg ripalais higanait maveekej baifavai gegohep
nujypysh.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
----#--
-#-###-
-###-#-
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:nahaisheed @[2 2]
#+END_SRC
** med
gaeg gaifeevyj siledog.

#+NAME: runes
#+BEGIN_SRC txt
-------
-###-##
-#-#-#-
-###-#-
--#--#-
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:med @[3 2]
#+END_SRC
** nip
hukeeb semol zhuchyn.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
----#--
-####--
-#--#--
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:nip @[4 2]
#+END_SRC
** shaichorip
wil caecozheh paben dagos wai zefa gaekocash.

#+NAME: runes
#+BEGIN_SRC txt
-------
##-####
-#---#-
-----#-
-#-###-
####---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:shaichorip @[5 2]
#+END_SRC
** hetachae
lamev cucaif docyzhev wukydi pozedaech sudeech bizaim.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
--#--#-
-##--#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:hetachae @[6 2]
#+END_SRC
** jofaep
vaig weeriduk johobaep.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
--####-
-----#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:jofaep @[7 2]
#+END_SRC
** fyshee
to ca fakatae gaik.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
--####-
--#--#-
-----#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:fyshee @[0 3]
#+END_SRC
** jupyshaet
beez daedai sher sa.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-###-#-
-----#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:jupyshaet @[1 3]
#+END_SRC
** bechak
wosegeep tyk tiwae fad ca dosuf fakaej seefaeban haisymaeh.

#+NAME: runes
#+BEGIN_SRC txt
-------
###-###
-#---#-
-#####-
-#-#-#-
-#-###-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:bechak @[2 3]
#+END_SRC
** baechived
fas chuwyhais haijyg zhezitaet shop jaigitizh faelae
zhaishaig shacoc.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-#-#-
-#---#-
-##----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:baechived @[3 3]
#+END_SRC
** wypen
ca chyfug rifosh dan hapy zhomer.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
-#####-
---#-#-
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:wypen @[4 3]
#+END_SRC
** kaekaek
zhyjaif wiceev mozy hi bae.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-###-
-#---#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:kaekaek @[5 3]
#+END_SRC
** suchai
taepyt seefikaem zopeev ludu ceeh.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
---#---
-###---
-#-###-
-###---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:suchai @[6 3]
#+END_SRC
** paipuchev
saiche ty pukyr shelee mydevoch.

#+NAME: runes
#+BEGIN_SRC txt
--------
#######
---#---
---###-
---#---
--####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:paipuchev @[7 3]
#+END_SRC
** zaimep
lee jainaiz railyzhaem zhicoh.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-----#-
-#####-
-#-----
-#####-
---#-#-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:zaimep @[0 4]
#+END_SRC
** shaishik
jeesheezhai wesyb cydam feetun bairet.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
--#--#-
-#####-
-----#-
-#####-
-----#-
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:shaishik @[1 4]
#+END_SRC
** wozhish
laigivy jechaif jir kokanep heechaih zhabi maeshigysh
lael jih.

#+NAME: runes
#+BEGIN_SRC txt
-------
#-#-###
--#--#-
--##-#-
-----#-
-#####-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:wozhish @[2 4]
#+END_SRC
** ser
lonemae nywaih bykul shebaebaez.

#+NAME: runes
#+BEGIN_SRC txt
-------
##-#-##
---#-#-
-###-#-
-#-###-
-#-----
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ser @[3 4]
#+END_SRC
** ciweet
taguchaij geesheemi wap.

#+NAME: runes
#+BEGIN_SRC txt
-------
-##-###
-##-#--
----#--
-#####-
-#---#-
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:ciweet @[4 4]
#+END_SRC
** gaecaijag
zhaenigiv vichaiheb ka chicozec dic zige.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#---#-
-#####-
---#---
--##---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:gaecaijag @[5 4]
#+END_SRC
** neteevib
nec bod zhig jo let bochepaek hudich.

#+NAME: runes
#+BEGIN_SRC txt
-------
#######
-#-#-#-
-#-#-#-
---#-##
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:neteevib @[6 4]
#+END_SRC
** paizheez
zhoned fumo dosh zhaimaed.

#+NAME: runes
#+BEGIN_SRC txt
-------
###-###
-#---#-
-#####-
---#---
---#---
-------
#+END_SRC

#+NAME: entries
#+BEGIN_SRC janet
:raetaeteb @[7 4]
#+END_SRC
